const google = require('googleapis');
import * as fs from 'fs';
import logger from '../utils/logger';

export interface CaptionLine {
  start: number;
  duration: number;
  text: string;
}

/**
 * List available caption tracks for a video
 */
export async function listCaptions(yt: any,
  videoId: string
): Promise<
  Array<{ id: string; language: string; type: string; autoGenerated: boolean }>
> {
  try {
    const res = await yt.captions.list({
      part: ['snippet'],
      videoId,
    });

    return (res.data.items || []).map((item: any) => ({
      id: item.id,
      language: item.snippet.language,
      type: item.snippet.trackKind,
      autoGenerated: item.snippet.trackKind === 'ASR',
    }));
  } catch (err: any) {
    if (err.code === 404) return [];
    throw err;
  }
}

/**
 * Download a caption track as SRT format
 */
export async function downloadCaptionSRT(yt: any,
  captionId: string
): Promise<string> {
  const res = await yt.captions.download(
    {
      id: captionId,
      tfmt: 'srt',
    },
    { responseType: 'stream' }
  );

  return await new Promise<string>((resolve, reject) => {
    let data = '';
    (res.data as any).on('data', (chunk: Buffer) => {
      data += chunk.toString();
    });
    (res.data as any).on('end', () => resolve(data));
    (res.data as any).on('error', reject);
  });
}

/**
 * Parse SRT content into structured lines
 */
export function parseSRT(srtContent: string): CaptionLine[] {
  const lines: CaptionLine[] = [];
  const blocks = srtContent.trim().split(/\n\n+/);

  for (const block of blocks) {
    const parts = block.split('\n');
    if (parts.length < 3) continue;

    const timeMatch = parts[1].match(
      /(\d{2}):(\d{2}):(\d{2}),(\d{3})\s*-->\s*(\d{2}):(\d{2}):(\d{2}),(\d{3})/
    );
    if (!timeMatch) continue;

    const start = parseTime(timeMatch.slice(1, 4));
    const end = parseTime(timeMatch.slice(4, 7));

    const text = parts.slice(2).join(' ').replace(/\n/g, ' ');

    lines.push({
      start,
      duration: end - start,
      text,
    });
  }

  return lines;
}

function parseTime(parts: string[]): number {
  const h = parseInt(parts[0], 10);
  const m = parseInt(parts[1], 10);
  const s = parseFloat(`${parts[2]}.${parts[3]}`);
  return h * 3600 + m * 60 + s;
}

/**
 * Get plain transcript text
 */
export function getTranscriptText(lines: CaptionLine[]): string {
  return lines.map((l) => l.text).join(' ');
}
